# Generated by Django 3.0.3 on 2020-05-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('id_no', models.CharField(max_length=60)),
                ('tz', models.CharField(max_length=60)),
                ('date', models.DateTimeField(default='%Y-%m-%d %H:%M:%S')),
            ],
        ),
    ]
