# Generated by Django 3.0.3 on 2020-05-05 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_member_datenew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date',
        ),
        migrations.AlterField(
            model_name='member',
            name='datenew',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 11, 0, 4, 122940), verbose_name='%d-%m-%Y'),
        ),
    ]
