# Generated by Django 3.0.3 on 2020-05-05 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20200505_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='datenew',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 11, 1, 20, 184909)),
        ),
    ]
