# Generated by Django 3.0.3 on 2020-05-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20200505_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='datenew',
            field=models.DateField(default='%d %b, %Y'),
        ),
    ]
