# Generated by Django 3.0.3 on 2020-05-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20200505_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='datenew',
            new_name='date',
        ),
    ]
